### ISSUE TITLE
Errors with test_solstice_oelt on MSYS2 (GHA)

### ISSUE THREAD

**Issue by jdpipe** [SolarTherm/SolarTherm#107]
Our current build tests are failing with MSYS2 only, due to some issue with what looks like `import numpy` in run_solstice.py. 

I think that the issue is that the PATH setting is not being correctly transmitted in `run_py_func.c` (which gets compiled to `libst_solstice.so` by `SConscript` in `src/modelica`)

```
---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "D:/a\_temp\msys64\home\runneradmin\.local\lib\omlibrary\SolarTherm\Resources\Library/run_solstice.py", line 3, in <module>
    import numpy as np
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 38, in init numpy.random.bit_generator
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/secrets.py", line 15, in <module>
    import base64
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/base64.py", line 11, in <module>
    import binascii
ImportError: DLL load failed while importing binascii: The specified module could not be found.
```

**Comment by jdpipe** [comment]
See also #103

**Comment by jdpipe** [comment]
I have tracked down a bug in MSYS2 Python which seems to be causing this error.
https://github.com/msys2/MINGW-packages/issues/18984.

**Comment by jdpipe** [comment]
marking as resolved. this was an issue in MSYS2's version of Python which we have figured out how to work around. eventually MSYS2 will be patched and we will be able to revert the workaround.
