### ISSUE TITLE
st_sensitivity: 'Worksheet' object has no attribute 'iter_cols'

### ISSUE THREAD

**Issue by arfontalvoANU** [SolarTherm/SolarTherm#77]
After running the following command on the Linux terminal:

`st_sensitivity Reference_2.mo --excel /home/arfontalvo/program_files/multiprocessing/examples/Reference_2_params.xlsx --wd /home/arfontalvo/sensitivity`

It shows the following error:
```
Traceback (most recent call last):
  File "/home/arfontalvo/.local/bin/st_sensitivity", line 91, in <module>
    params.load_values_from_excel(args.excel, tree)
  File "/home/arfontalvo/.local/lib/python2.7/site-packages/solartherm/params.py", line 306, in load_values_from_excel
    for col in ws.iter_cols(min_col=2,max_col=2,min_row=ws.min_row, max_row=ws.max_row): # look at cells in column 
AttributeError: 'Worksheet' object has no attribute 'iter_cols'
```

Machine: Optiplex 7050
System: Ubuntu 16.04
Python version: 2.7

**Comment by arfontalvoANU** [comment]
I solved the issue by removing openpyxl 2.3.0 from `/usr/lib/python2.7/dist-packages` using the sudo command:

`sudo python -m pip uninstall openpyxl`

And installing openpyxl 2.6.4 by running:

`python -m pip install openpyxl`

Now it runs correctly.
